// Converts the raw background screenshots into the optimized webp tiles used by
// the collage, skipping byte-identical duplicates, then regenerates the photo
// list the component imports.
//
//   node scripts/build-collage.mjs [sourceDir]
//
// sourceDir defaults to ../background (a sibling of this repo, not checked in).
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile, rm, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = path.resolve(fileURLToPath(import.meta.url), '../..');
const source = process.argv[2] ? path.resolve(process.argv[2]) : path.resolve(root, '../background');
const target = path.join(root, 'public/collage');
const listFile = path.join(root, 'lib/collage-photos.ts');

function slug(file) {
  return path.parse(file).name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/^(\d)/, 'img-$1');
}

const files = (await readdir(source)).filter((file) => /\.(png|jpe?g|webp)$/i.test(file)).sort();
const seen = new Map();
const skipped = [];
for (const file of files) {
  const hash = createHash('sha256').update(await readFile(path.join(source, file))).digest('hex');
  if (seen.has(hash)) { skipped.push(`${file} == ${seen.get(hash)}`); continue; }
  seen.set(hash, file);
}

await rm(target, { recursive: true, force: true });
await mkdir(target, { recursive: true });

const names = [];
for (const file of seen.values()) {
  const name = slug(file);
  await sharp(path.join(source, file))
    .resize({ width: 560, height: 560, fit: 'inside', withoutEnlargement: true })
    .webp({ quality: 72 })
    .toFile(path.join(target, `${name}.webp`));
  names.push(name);
}
names.sort();

await writeFile(
  listFile,
  `// Generated by scripts/build-collage.mjs — do not edit by hand.\n` +
  `export const photos = [\n${names.map((name) => `  '${name}',`).join('\n')}\n];\n`,
);

console.log(`sources: ${files.length}, byte-duplicates skipped: ${skipped.length}, written: ${names.length}`);
for (const line of skipped) console.log('  dup:', line);
